### ISSUE TITLE
Provide list of themes for sunset/sunrise/timeslot

### ISSUE THREAD

**Issue by guidoschmidt** [guidoschmidt/circadian.el#16]
Allow setting a list of themes, that should get loaded on a timeslot (or sunset/sunrise). When loading a theme, it should randomly get selected from that list

**Comment by eitazhou** [comment]
` 
(use-package circadian
  :ensure t
  :config
  (setq calendar-latitude 44.0)
  (setq calendar-longitude 25)
  (setq circadian-themes '((:sunrise . (funcall (nth (random 2) '(solarized-light spacemacs-light))))
                           (:sunset  . (funcall (nth (random 2) '(solarized-dark  spacemacs-darks))))))
  (circadian-setup)) 

`


However, it doesn't work  :-(

**Comment by lemyx** [comment]
The feature is awesome, if supported

**Comment by BBoal** [comment]
@eitazhou your binding of circadian-themes doesn't look good.
Try this instead:

``(setq circadian-themes `((:sunrise . ,(nth (random 2) '(solarized-light spacemacs-light)))
                         (:sunset . ,(nth (random 2) '(solarized-dark spacemacs-darks)))))``

Hope it helps!

**Comment by guidoschmidt** [comment]
@BBoal thanks for providing this simple solution. I'm currently working on supporting list of themes
