### ISSUE TITLE
How to override or stop circadian?

### ISSUE THREAD

**Issue by infinitebuffalo** [guidoschmidt/circadian.el#24]
I set up and initialized Circadian as suggested, but then decided I wanted for the moment to use a different theme.  However, circadian doesn't allow the theme to be reset -- it's not that attempting to set the theme _fails_ exactly, but after load-theme completes, circadian changes it back.  

I don't even seem to be able to figure out how to turn off circadian so I can set a different theme, temporarily _or_ permanently.  Even uninstalling the package doesn't seem to kill it--or allow me to change themes....

So, 

1. How does one override or pause circadian so you can change to a different theme temporarily?  
2. How does one stop or disable circadian?  Once started, does it just run without end until emacs itself is terminated or restarted?

**Comment by guidoschmidt** [comment]
- You should [re-read about how to change themes in Emacs](https://www.gnu.org/software/emacs/manual/html_node/emacs/Custom-Themes.html)
- You should read and learn about how to use, install and uninstall Emacs packages and how to enable and disable them in your `init.el`. Try to use a package manager like [use-package.el](https://github.com/jwiegley/use-package#conditional-loading) or [straight.el](https://github.com/radian-software/straight.el), which will give you simpler possibilties to disable packages, e.g. the [:disabled](https://github.com/jwiegley/use-package#conditional-loading) feature of use-package.
- Try `M-x load-theme` or `M-x counsel-load-theme` (if you use [counsel](https://oremacs.com/2015/04/09/counsel-completion/)). Oou should be able to select another theme to overwrite themes set by circadian. If this doesn't work, there must be something very wrong in your configuration file.
