### ISSUE TITLE
Theme change scheduled to wrong day.

### ISSUE THREAD

**Issue by jumper047** [guidoschmidt/circadian.el#25]
I have two entries in circadian themes:
```
(setq circadian-themes '(("09:00" . 'theme-one) ("18:00". 'theme-two)))
```
When I launched my Emacs in 08:30, theme-two was applied, but switch to theme-one was planned on 09:00 of the next day.
Just in case I'll put here workaround (until proper bugfix) - just add entry ("00:01" . 'theme-two) to circadian themes.

**Comment by guidoschmidt** [comment]
Alright, took me some time to reproduce that issue. I'm using circadian solely with `:sunrise` and `:sunset` settings, which is the reason I didn't experience that behaviour.
However your PR seems to have fixed the issue 👏🏽 thanks for putting it up. I'm about to release a new version today or the other day, after I finally got some time to setup github actions, too as well as improved the test suite a bit.
